[package]
cairo-version = "2.4.0"
name = "number_game"
version = "0.0.1"

[cairo]
sierra-replace-ids = true

[dependencies]
pixelaw = { git = "https://github.com/pixelaw/core" }

[[target.dojo]]
build-external-contracts = [
    "pixelaw::apps::snake::app::snake",
    "pixelaw::apps::snake::app::snake_segment",
    "pixelaw::core::models::pixel::pixel",
    "pixelaw::core::models::pixel::Pixel",
    "pixelaw::core::models::pixel::PixelUpdate",
    "pixelaw::core::models::queue::queue_item",
    "pixelaw::core::models::registry::app",
    "pixelaw::core::models::registry::app_name",
    "pixelaw::core::models::registry::app_user",
    "pixelaw::core::models::registry::app_instruction",
    "pixelaw::core::models::registry::instruction",
    "pixelaw::core::models::registry::core_actions_address",
    "pixelaw::core::models::permissions::permissions",
    "pixelaw::core::utils::get_core_actions",
    "pixelaw::core::utils::Direction",
    "pixelaw::core::utils::Position",
    "pixelaw::core::utils::DefaultParameters",
    "pixelaw::core::actions::actions",
    "pixelaw::core::actions::IActionsDispatcher",
    "pixelaw::core::actions::IActionsDispatcherTrait"
]

[tool.dojo]
initializer_class_hash = "0xbeef"

[scripts]
ready_for_deployment = "bash ./scripts/ready_for_deployment.sh"
initialize = "bash ./scripts/default_auth.sh"
upload_manifest = "bash ./scripts/upload_manifest.sh"
ready_for_deployment_zsh = "zsh ./scripts/ready_for_deployment.sh"
initialize_zsh = "zsh ./scripts/default_auth.sh"
upload_manifest_zsh = "zsh ./scripts/upload_manifest.sh"

[tool.dojo.env]
rpc_url = "http://localhost:5050/"

account_address = "0x517ececd29116499f4a1b64b094da79ba08dfd54a3edaa316134c41f8160973"
private_key = "0x1800000000300000180000000000030000000000003006001800006600"
